fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "max.kytsenyuk@gmail.com"
        sender_name: "max.kytsenyuk@gmail.com"
    registration:
        form:
            type: 'App\Form\Type\RegistrationFormType'